Cryptocurrency
SimonGrchevski/Cryptocurrency pull request #5
Opened 2021-09-10 21:03 UTC by SimonGrchevski

- Add the React Components
- Add the Redux logic 
- Add the styles
- Use MSW to intercept the API calls, and Add All the tests
- Write the README.md

2021-09-11 03:11 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please try to add proper tests in your project. This is one of the basic requirements for the project. 
- [ ] It would begreat if you can add filter stateless. Please check the requirements once again. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-11 08:31 UTC, SimonGrchevski commented
> # Changes Requested,
> Hi there,
> 
> Good job so far!
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider:
> 
> * [ ]  Please try to add proper tests in your project. This is one of the basic requirements for the project.
> * [ ]  It would begreat if you can add filter stateless. Please check the requirements once again.
> 
> Cheers and Happy coding!
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-11 08:34 UTC, SimonGrchevski commented
Note:
I see no comments therefore please consider to kindly review.

2021-09-11 08:52 UTC, arslanbisharat commented
> Note:
> I see no comments therefore please consider to kindly review.

Please read my comment once again.

2021-09-11 09:01 UTC, SimonGrchevski commented
I did it. There is no comment.

2021-09-11 09:07 UTC, arslanbisharat commented
> I did it. There is no comment.

Please try to add proper tests in your project. This is one of the basic requirements for the project. It would begreat if you can add filter stateless. Please check the requirements once again.

2021-09-11 09:09 UTC, SimonGrchevski commented
They are all labeled as Optional.

" You can also consider:

 Please try to add proper tests in your project. This is one of the basic requirements for the project.
 It would begreat if you can add filter stateless. Please check the requirements once again. "

2021-09-11 09:17 UTC, arslanbisharat commented
These are not optional. I cannot use comments for these requirements so
these are in this section. Hope this helps.

On Sat, Sep 11, 2021, 2:09 PM Simon G. ***@***.***> wrote:

> They are all labeled as Optional.
>
> " You can also consider:
>
> Please try to add proper tests in your project. This is one of the basic
> requirements for the project.
> It would begreat if you can add filter stateless. Please check the
> requirements once again. "
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/SimonGrchevski/Cryptocurrency/pull/5#issuecomment-917372640>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN6LLT4MOLRH6UBRBWT4X7DUBMMFPANCNFSM5D2DJP3Q>
> .
>

2021-09-11 11:06 UTC, mikenath223 requested changes
Hi there, 

Awesome job on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. Let's work on those.


 ## Required Changes ♻️
_Kindly check the comments under the review._


Happy coding, Cheers!🚀🚀

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it's valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-11 11:08 UTC, mikenath223 commented on src/Components/MainPage.js
> +  );
- [ ] As requested in the previous review please add the filter component that should enable the user to filter the data retrieved by different values.

2021-09-11 11:10 UTC, mikenath223 commented on .eslintrc.json
> +    ]
- [ ] Kindly use the same eslint rules listed [here](https://github.com/microverseinc/linters-config/tree/master/react-redux).

2021-09-11 11:11 UTC, mikenath223 commented on src/Components/CurrencyDetail.js
> +        </div>
- [ ] OPTIONAL - Consider adding margin/padding to the details listed.

<img src="https://user-images.githubusercontent.com/33323077/132945930-1f43ab5a-4278-472d-96fd-8d37004b2a79.png" height="250px"/>

2021-09-11 13:23 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @SimonGrchevski,

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :male_detective: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-11 16:46 UTC, merged

2021-09-13 09:22 UTC, nidalaa commented
Hello @SimonGrchevski ,

_This message is a result of the second opinion request_

Due to the bug, your request was lost and restored only today. We apologize for the inconvenience.

As I can see - you and Code Reviewers managed to clarify requirements. Good job here!